### ISSUE TITLE
Can I use library with HttpWebRequest?

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [XieJJ99/brotli.net#1]
HttpWebRequest have "AuthomaticDecompression" field, can I set something like 
instance.AuthomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate | Brotli.Br ? Is there way to do so?

**Comment by ericnewton76** [comment]
You would use BrotliStream to compress the data while sending a Response, via Response.GetResponseStream.  

You have to check Accept-Encoding headers sent during Request though, for "br"

Assuming thats true, you can do something like:

```
    //req comes from HttpWebRequest GetRequest
    //memorystream contains whatever you wanted to send.
    var resp = req.GetResponse()
    using(var outputStream = new BrotliStream(resp.GetResponseStream(), CompressionMode.Compress)) {
     
         memoryStream.CopyTo(outputStream);

    }
```

Key is resp.GetResponseStream() and using that returned Stream in the ctor for BrotliStream
