### ISSUE TITLE
The code in the README.md is full of errors

### ISSUE THREAD

**Issue by ANUBIS-V** [XieJJ99/brotli.net#11]
Did anyone really tested with this code?

**Comment by XieJJ99** [comment]
@kongyuan ,have you run the unit test?

**Comment by Zeokat** [comment]
Yeah the code in Readme.md has errors, one that you can see fast is on Decompress example, where no `output` var is defined.

**Comment by jiangyz7cc** [comment]
Yeah, Does this lib has problems?
I've tried these:

> 		//msin.CopyTo(bs);
> 		//msin.Read(buf, 0, buf.Length);
> 		bs.Write(buf, 0, buf.Length);
> 		dataenc = msou.ToArray();

I've got: dataenc={0}? and bs.Length can't be read...
How can I use BrotliStream in this lib correctly?

**Comment by XieJJ99** [comment]
@jiangyz7cc Are you compress the data? To get the compressed data, you should use bs.Close to close the brotli stream first, and then use ToArray() to get the data.
> Yeah, Does this lib has problems?
> I've tried these:
> 
> > ```
> >   //msin.CopyTo(bs);
> >   //msin.Read(buf, 0, buf.Length);
> >   bs.Write(buf, 0, buf.Length);
> >   dataenc = msou.ToArray();
> > ```
> 
> I've got: dataenc={0}? and bs.Length can't be read...
> How can I use BrotliStream in this lib correctly?

**Comment by jiangyz7cc** [comment]
> 
> 
> @jiangyz7cc Are you compress the data? To get the compressed data, you should use bs.Close to close the brotli stream first, and then use ToArray() to get the data.
> 
> > Yeah, Does this lib has problems?
> > I've tried these:
> > > ```
> > >   //msin.CopyTo(bs);
> > >   //msin.Read(buf, 0, buf.Length);
> > >   bs.Write(buf, 0, buf.Length);
> > >   dataenc = msou.ToArray();
> > > ```
> > 
> > 
> > I've got: dataenc={0}? and bs.Length can't be read...
> > How can I use BrotliStream in this lib correctly?

For me, that's the close() problem.
After, I found that I wrote like:
using(...)
using(...)

Then I chang to:
using(...){
    using(...){
    }
}
then it works (can get data from the brotil stream).
probably cause "bs" wasn't closed, it need to be closed to get the data array.
