### ISSUE TITLE
BrotliStream.Flush() writes two bytes to an empty stream

### ISSUE THREAD

**Issue by trullock** [XieJJ99/brotli.net#12]
The following test fails in two unexpected (perhaps) ways

```
[TestMethod]
public void EmptyStream()
{
	var memoryStream = new MemoryStream();
	var brotliStream = new BrotliStream(memoryStream, CompressionMode.Compress, true);
	brotliStream.Flush();
	Assert.AreEqual(0, memoryStream.Length); // Fails, Length == 2


	memoryStream.Position = 0;
	using (var bs = new BrotliStream(memoryStream, CompressionMode.Decompress))
	using (var msOutput = new MemoryStream())
	{
		bs.CopyTo(msOutput); // goes bang
		msOutput.Seek(0, SeekOrigin.Begin);
		var output = msOutput.ToArray();
		Assert.AreEqual(0, output.Length);
	}
}
```

First, flushing an empty stream produces 2 bytes. 

This comes from inside both ` Brolib32.BrotliEncoderCompressStream` and ` Brolib.BrotliEncoderCompressStream`

Is this expected behaviour? This is a problem/unexpected when setting `HttpResponse.Filter` to add Brotli compression to an ASP.NET web application.

Perhaps this is an expected feature of Brotli, however, decoding those two bytes then causes an exception of `Not Enough Information`, which ordinarily I'd have said was likely, except I'm decoding output Brotli created.

I appreciate this is coming from inside Brotli and not Brotli.NET, but its still an issue.

Other than keeping a track inside BrotliStream as to whether `.Write()` as been called, and then doing "nothing" inside `Flush()`, is there a solution?

**Comment by trullock** [comment]
Opened a PR for this, not 100% sure if its the right solution, but it demos my point if nothing else

**Comment by XieJJ99** [comment]
@trullock Thanks for the comment.
You should close the brolit stream before get bytes.
The follow code should works:
```
            using (var memoryStream = new MemoryStream())
            {
                **using (var brotliStream = new BrotliStream(memoryStream, CompressionMode.Compress, true))
                {
                    brotliStream.Flush();
                }**
                memoryStream.Seek(0, SeekOrigin.Begin);
                var data = memoryStream.ToArray();
                using (var bs = new BrotliStream(memoryStream, CompressionMode.Decompress))
                using (var msOutput = new MemoryStream())
                {
                    bs.CopyTo(msOutput); // goes bang
                    msOutput.Seek(0, SeekOrigin.Begin);
                    var output = msOutput.ToArray();
                    Assert.True(output.Length == 0);
                }
            }
```
