### ISSUE TITLE
System.BadImageFormatException: Could not load file or assembly 'brolib32' or one of its dependencies

### ISSUE THREAD

**Issue by dyardyGIT** [XieJJ99/brotli.net#14]
We have .NET 4.6.1 web application (asp.net mvc) using Brotli.NET v.1.0.19 and catching these exceptions.

Any ideas on how to resolve?

System.BadImageFormatException: Could not load file or assembly 'brolib32' or one of its dependencies. The module was expected to contain an assembly manifest.
  at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName
  at System.Reflection.RuntimeAssembly.InternalLoad
  at System.Reflection.RuntimeAssembly.InternalLoad
  at System.Reflection.Assembly.Load
  at System.Web.Configuration.CompilationSection.LoadAssemblyHelper

And

System.BadImageFormatException: Could not load file or assembly 'brolib64' or one of its dependencies. The module was expected to contain an assembly manifest.
  at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName
  at System.Reflection.RuntimeAssembly.InternalLoad
  at System.Reflection.RuntimeAssembly.InternalLoad
  at System.Reflection.Assembly.Load
  at System.Web.Configuration.CompilationSection.LoadAssemblyHelper

**Comment by XieJJ99** [comment]
The exceptions shows that it can't load the native dll.
The assembly will try to load brolib32 on x86 or brolib64 on x64.
Can you see the brolib32.dll/brolib64.dll under the Bin directory?

**Comment by XieJJ99** [comment]
@dyardyGIT Version 2 is released, which is supporting .net standard2.
Will you have a try on this version?
Thanks.

**Comment by XieJJ99** [comment]
@dyardyGIT Could you kindly test against the latest version **v2.0.4** so that I could close the issue?

**Comment by MarcinZiabek** [comment]
@XieJJ99 @dyardyGIT Hi, first of all, I need to mentation that I and dyardy are working on the same project so please consider mine response as his ;)

Let's begin with a little bit more details about the environment and behaviour of the library. The application that uses the Brotli.NET library is a web application hosted on a local IIS server (not an Express version) and is based on the .NET Framework 4.6.1.

Brotli.NET version 1.0.19 was being used in the application nearly successfully. The System.BadImageFormatException mentioned by dyardy was being thrown during code execution but the functionality was working (we have been able to compress and decompress data). Sometimes, we have similar exceptions connected to SkiaSharp library which works as well. Those exceptions are usually thrown only once when the application starts.

When I updated Brotli.NET to version 2.0.4 the functionality broke. On a clear nuget install and bin folder cleaned, the native files are copied into WEB_PROJECT_PATH/bin/runtimes/win/native folder and we are getting the following exception:

```
System.TypeInitializationException: The type initializer for 'Brotli.Brolib64' threw an exception.
System.TypeInitializationException: The type initializer for 'Brotli.LibPathBootStrapper' threw an exception.
System.NotSupportedException: Unable to find library brolib_x64.dll at Brotli.LibPathBootStrapper..cctor()

End of inner exception stack trace at Brotli.LibPathBootStrapper.get_LibPath() at Brotli.Brolib64..cctor()
```

When I additionally copy those dll files into WEB_PROJECT_PATH/bin the exception is different:

```
Could not load file or assembly 'brolib_x64' or one of its dependencies. The module was expected to contain an assembly manifest.
```

I suspect that this problem maybe similar to https://github.com/XieJJ99/brotli.net/issues/16 where the difference is environment. Previously you have found a solution regarding NUnit runner - maybe this time it is connected to IIS. If more information is needed, please feel free to ask ;)

**Comment by XieJJ99** [comment]
@dyardyGIT @MarcinZiabek  Thanks for the help.
Indeed it's the issue with IIS enviroment. We need to add the AppDomain.CurrentDomain.BaseDirectory to the search path.
Could you kindly try v2.0.4.2 ? I have already tested it with both of IIS Express and local IIS.

**Comment by MarcinZiabek** [comment]
@XieJJ99 @dyardyGIT I updated the Brotli.NET library to version 2.0.4.2. I was able to reproduce the System.BadImageFormatException exception for the SkiaSharp library but it is NOT being thrown for Brotli.NET any more. That means the issue can be considered as resolved. I suspect that we will push the update to production in the nearest days and in case of any problems, let you know. Congratulations and thanks for your great support!

**Comment by XieJJ99** [comment]
@MarcinZiabek @dyardyGIT Thanks for the help and confirmation.  In general the System.BadImageFromatException occurs when an assembly trying to load an assembly didn't match current architect. For example, trying to load a 32-bit assembly within a 64-bit environment will throw this exception. Set Enable32BitAppOnWin64 to true on the IIS pool may reduce the exception.
