### ISSUE TITLE
PDBs are declared in the Nuget packages as a runtime dependency?

### ISSUE THREAD

**Issue by threenub** [XieJJ99/brotli.net#19]
Hi,

When we consume the Brotli.NET package 2.0.4.2 in our NetCoreApp2.1 project the PDB debugging symbol files are being declared as runtime dependencies?

`
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.1/win-x64",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v2.1": {},
    ".NETCoreApp,Version=v2.1/win-x64": {
      "MyProject/1.0.0": {
        "dependencies": {
        },
        "runtime": {
          "MyProject.dll": {}
        }
      },
      "Brotli.NET/2.0.4.2": {
        "runtime": {
          "lib/netstandard2.0/Brotli.Core.dll": {
            "assemblyVersion": "2.0.4.2",
            "fileVersion": "2.0.4.2"
          }
        },
        "native": {
          "runtimes/win/native/brolib_x64.dll": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win/native/brolib_x64.pdb": {   // This is one PDB
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win/native/brolib_x86.dll": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win/native/brolib_x86.pdb": {  // .. and this the other PDB
            "fileVersion": "0.0.0.0"
          }
        }
      }
`

**Comment by XieJJ99** [comment]
Thanks for the report, the pdb files are removed since v2.1.1 .
