### ISSUE TITLE
Nuget is out of date?

### ISSUE THREAD

**Issue by otryshko** [XieJJ99/brotli.net#20]
When I look at the code of Brotli.net 2.0.4.2 nuget, the code seems to be very different. For example, there is no SetQuality method on Brotli stream. Is there a more recent nuget?

**Comment by XieJJ99** [comment]
Which platform are you targeting?
I had just downloaded the package, and the SetQuality method is available.

**Comment by XieJJ99** [comment]
Close the issue due to timeout.
