### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by RehanSaeed** [XieJJ99/brotli.net#4]
Could .NET Core support be added? I noticed you are interoping with the native brotli DLL, so it would be a matter of including native DLL's for all the platforms. If you take a look at the ASP.NET Core [libuv](https://github.com/aspnet/libuv-build) project, they created a NuGet package containing just native libuv.dll files for each platform and then used that package to create C# wrappers.

There is also a Java port of the brotli decoder, so it should be fairly simple to translate that to C# and get a fully managed class library.

**Comment by SergioLuis** [comment]
@RehanSaeed Can you provide a link to the Java Brotli decoder you are referring to? Thank you!

**Comment by RehanSaeed** [comment]
https://github.com/google/brotli

**Comment by RehanSaeed** [comment]
It should be noted that the Java port is only a decoder and not an encoder.

**Comment by master131** [comment]
I've had this project laying around for a few months now and have decided to release it on GitHub, it's a full C# port of brotli that doesn't use an unmanaged binaries - it's a mostly 1:1 conversion of the original C code. Currently it only supports decompression but if you want to check it out it's here:
https://github.com/master131/BrotliSharpLib

There is also the reference implementation that I noticed Google released recently, it uses sharpen to convert the Java implementation straight to C#. Don't know how fast it is though:
https://github.com/google/brotli/tree/master/csharp

**Comment by XieJJ99** [comment]
@RehanSaeed @SergioLuis @master131  Thanks for the update and contribution. Google already release a pure C# brotli decoder and the encoder is on the way.  We'll watch the progress and compare the performance between the  interop version and the native version then.   The encoding performance is critical for web applications.

**Comment by RehanSaeed** [comment]
@XieJJ99 Thanks for the update. Looking forward to the C# encoder.

**Comment by master131** [comment]
@XieJJ99 [BrotliSharpLib](https://github.com/master131/BrotliSharpLib) now has a native C# encoder; benchmarks are at the bottom of the README. For best performance, at least at the highest quality levels, interop/C version is better.

**Comment by trullock** [comment]
I've just updated my PR to include netstandard2.0 support, see my fork if you want dem codez

**Comment by XieJJ99** [comment]
@trullock @master131 @SergioLuis Thanks for the suggestion and feedback.
Now v2.0 is released, .net standard 2 is supported.
This means .net Framework v4.6.1 and .net core 2.0 are supported.
