### ISSUE TITLE
Older .NET Support (2.0)

### ISSUE THREAD

**Issue by drivehappy** [XieJJ99/brotli.net#5]
It would be ideal to support older versions of .NET. I quickly checked and it seems by just removing the Linq using namespaces (which appear to be unused) that the project builds under .NET 2.0.

Would you be willing to take a PR to change this? If desired I can look into building it both for net20 and net40 for NuGet.

**Comment by XieJJ99** [comment]
@drivehappy thanks for the suggestion. Now both of .NET 2.0 and .NET 4.0 are supported, please check version 1.0.12 on nuget.
