### ISSUE TITLE
Could not load file or assembly 'broclr2_32' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by ksysiekj** [XieJJ99/brotli.net#7]
hi,
Wanted to use Brotli.NET but i'm getting 
_Could not load file or assembly 'broclr2_32' or one of its dependencies. An attempt was made to load a program with an incorrect format._ 
exception
 
 Assembly Binder Log:
LOG: Entering download cache setup phase.
LOG: Assembly Name is: broclr2_64, Version=1.0.6290.16951, Culture=neutral, PublicKeyToken=null
ERR: Invalid assembly platform or ContentType in file (hr = 0x8007000b).
ERR: Setup failed with hr = 0x8007000b.
ERR: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

my aplication targets .net 4.5.2 , platform target Any CPU

**Comment by XieJJ99** [comment]
@ksysiekj  thanks for the feedback, this is probably due to the lack of VC runtime library. I'll investigate this issue soon. Please use v1.0.12 instead.

**Comment by XieJJ99** [comment]
@ksysiekj Since your issue duplicate with #6, I will close the issue first. You can use the stable version v1.0.12 #6 is fixed.
